version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: dbmv
  app:
    image: movie-app
    ports:
      - 13000:3000
