###
GET http://localhost:13000/setup
###

POST http://localhost:13000/setup

###
GET http://localhost:13000

###
POST http://localhost:13000/
Content-Type: application/json

  [{
    "Title": "Pokémon: The First Movie - Mewtwo Strikes Back",
    "Year": "1998",
    "imdbID": "tt0190641",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BZGM3MjQ3NTQtNzRiZi00MDUzLWFjYjEtZWJjMjUwYzExYjRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  }]
